### PR TITLE
Fix invalid date being accepted

### LINKED ISSUE #164: [PE-D][Tester A] Wrong meeting date (but correct format) allowed to be added into the meetings list
* A wrong date (but correct format) was being input into the command line
  * `addm m/CS2103T Tutorial p/Alex Yeoh dt/31/02/2022 10:00 l/COM1-B103 des/CS2103T Tutorial`

* Notice the date added is `31/02/2022`, which is in the correct format, but 31st do not exist in the month of February
* Upon keying the command, an entry is added into the meetings list, but the date is instead changed to `28/02/2022`

<i><video controls><source src="https://raw.githubusercontent.com/YZmunchmunch/ped/main/files/e88980cd-ef2e-4c34-9803-570b5632a9c5.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/YZmunchmunch/ped/main/files/e88980cd-ef2e-4c34-9803-570b5632a9c5.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YZmunchmunch/ped#2

### PR DESCRIPTION
**Pull request by Beebeeoii**
This PR fixes #164.

Previously, QuickContacts will still go ahead and create a meeting with an invalid date, for example `31/02/2023` by automatically changing it to `28/02/2023`. Similarly, for dates like `31/04/2023` will be automatically changed to the last valid date of that month, in this case, `30/04/2023`.

This PR fixes that by having a `strict` check for the dates.

### CODE REVIEW

File: src/test/java/seedu/quickcontacts/model/meeting/DateTimeTest.java [hunk 1]
```diff
@@ -83,6 +86,9 @@ public void isValidDateTime() {
         assertTrue(DateTime.isValidDateTime("22/05/2023 13:22"));
         assertTrue(DateTime.isValidDateTime("22/05/2023 1:32AM"));
         assertTrue(DateTime.isValidDateTime("22/05/2023 12:32PM"));
+        assertTrue(DateTime.isValidDateTime("28/02/2023")); // all februarys have 28 days
+        assertTrue(DateTime.isValidDateTime("01/01/2023")); // first day of a month
+        assertTrue(DateTime.isValidDateTime("31/01/2023")); // last day of a month
```
Comment (KS2499) [inline src/test/java/seedu/quickcontacts/model/meeting/DateTimeTest.java:91]:
```suggestion
        assertTrue(DateTime.isValidDateTime("31/01/2023")); // last day of a month
        assertTrue(DateTime.isValidDateTime("29/02/2020")); // leap year extra day True
```

**Review by KS2499 — CHANGES_REQUESTED** [review]
LGTM! Just an additional test case to cover leap year.

**Review by KS2499 — APPROVED** [review]
